on:
  push:
    branches:
      - master





jobs:
  build:
    runs-on: ubuntu-latest


    steps:

      - uses: actions/checkout@v3


      - name: "login to dockerHub"
        run: docker login --username meslhy --password dckr_pat_8uurZk228R4DKbl9hcHtSaOIFYY



