on:
  push:
    branches:
      - master





jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: 'printing folders contacts before'
        run: ls

      - uses: actions/checkout@v3


      - name: 'printing folders contacts after'
        run: ls -a
